<?php

declare(strict_types=1);

// Generated by `npm run brand:build` from docs/design/logo-source.png. Do not edit by hand.
// Sizes are CSS pixels (the 1x files); @2x files have twice as many pixels.

return [
    'version' => 'cae760d4b8',
    'source' => 'docs/design/logo-source.png',
    'cleared_pixels' => 66809,
    'variants' => [
        'logo-full' => [
            'width' => 320,
            'height' => 75,
        ],
        'logo-compact' => [
            'width' => 225,
            'height' => 44,
        ],
        'logo-mark' => [
            'width' => 64,
            'height' => 64,
        ],
        'logo-compact-boxed' => [
            'width' => 241,
            'height' => 60,
        ],
        'logo-email' => [
            'width' => 200,
            'height' => 39,
        ],
        'og-image' => [
            'width' => 1200,
            'height' => 630,
        ],
    ],
];
